/* Error codes */

#ifndef COMMON_ERRORS_H_
#define COMMON_ERRORS_H_

typedef enum
{
	ERROR_INVALID,
	ERROR_ARM9_FIFO_BUFF_SIZE,
	ERROR_ARM9_FIFO_SEND,
	ERROR_ARM9_FIFO_RECEIVE,
	ERROR_ARM9_FIFO_INVALID_COMMAND,
	ERROR_ARM7_FIFO_BUFF_SIZE,
	ERROR_ARM7_FIFO_SEND,
	ERROR_ARM7_FIFO_RECEIVE,
	ERROR_ARM7_FIFO_INVALID_COMMAND,
	ERROR_MP3_END_OF_FILE,
	ERROR_MP3_DECODE,
	ERROR_MP3_CHUNK_SIZE,
} Errors_e;


#endif /* COMMON_ERRORS_H_ */
